"""Add buying_price and reorder_level to Product

Revision ID: 1fc833a7651e
Revises: beb2e43dbb41
Create Date: 2025-11-16 21:55:32.989536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fc833a7651e'
down_revision = 'beb2e43dbb41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buying_price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reorder_level', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('reorder_level')
        batch_op.drop_column('buying_price')

    # ### end Alembic commands ###
